$ErrorActionPreference = "Stop"

$workspaceRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$auditPath = Join-Path $workspaceRoot "backend\docs\missing-image-source-audit.csv"
$webPath = Join-Path $workspaceRoot "backend\docs\missing-image-web-discovery.csv"
$manualPath = Join-Path $workspaceRoot "backend\docs\missing-image-manual-review.csv"
$ktoPath = Join-Path $workspaceRoot "backend\docs\missing-image-kto-review.csv"
$outputPath = Join-Path $workspaceRoot "db\danyeogam_external_images.sql"

function Sql-String([AllowNull()][string]$value) {
    if ([string]::IsNullOrWhiteSpace($value)) { return "NULL" }
    return "'" + ($value -replace "'", "''" -replace '\\', '\\\\') + "'"
}

$approved = [System.Collections.Generic.List[object]]::new()

Import-Csv -LiteralPath $auditPath |
    Where-Object { $_.Status -in @('APPROVED', 'APPROVED_REHOST_REQUIRED') } |
    ForEach-Object {
        $approved.Add([pscustomobject]@{
            TouristSpotId = [long]$_.TouristSpotId
            Name = $_.Name
            ImageUrl = $_.ImageUrl
            SourcePageUrl = $_.SourcePageUrl
            CopyrightType = $_.LicenseCode
            LicenseUrl = $_.LicenseUrl
            Provider = $_.Provider
            Attribution = $_.Attribution
            VerifiedAt = $_.VerifiedAt
            SourceImageId = "verified-source:$($_.TouristSpotId)"
        })
    }

Import-Csv -LiteralPath $webPath |
    Where-Object { $_.Status -like 'APPROVED*' } |
    ForEach-Object {
        $copyrightType = if ($_.Status -eq 'APPROVED_TOURAPI_INDEX') { 'TOURAPI_WEB_INDEX' } else { 'OFFICIAL_WEB' }
        $provider = if ($_.Status -eq 'APPROVED_TOURAPI_INDEX') { '한국관광공사 대한민국 구석구석' } else { $_.ProviderHost }
        $approved.Add([pscustomobject]@{
            TouristSpotId = [long]$_.TouristSpotId
            Name = $_.Name
            ImageUrl = $_.ImageUrl
            SourcePageUrl = $_.SourcePageUrl
            CopyrightType = $copyrightType
            LicenseUrl = ''
            Provider = $provider
            Attribution = "사진 출처: $provider"
            VerifiedAt = $_.VerifiedAt
            SourceImageId = "verified-web:$($_.TouristSpotId)"
        })
    }

@($manualPath, $ktoPath) | ForEach-Object { Import-Csv -LiteralPath $_ } |
    ForEach-Object {
        $approved.Add([pscustomobject]@{
            TouristSpotId = [long]$_.TouristSpotId
            Name = $_.Name
            ImageUrl = $_.ImageUrl
            SourcePageUrl = $_.SourcePageUrl
            CopyrightType = $_.LicenseCode
            LicenseUrl = $_.LicenseUrl
            Provider = $_.Provider
            Attribution = $_.Attribution
            VerifiedAt = $_.VerifiedAt
            SourceImageId = "verified-manual:$($_.TouristSpotId)"
        })
    }

$duplicates = @($approved | Group-Object TouristSpotId | Where-Object Count -gt 1)
if ($duplicates.Count -gt 0) {
    throw "Duplicate tourist spot ids: $($duplicates.Name -join ', ')"
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('-- Generated by scripts/build-verified-tourist-image-sql.ps1')
$lines.Add('-- Sources and verification evidence are recorded under backend/docs/.')
$lines.Add('SET NAMES utf8mb4;')
$lines.Add('START TRANSACTION;')

foreach ($item in @($approved | Sort-Object TouristSpotId)) {
    $spotId = $item.TouristSpotId
    $url = Sql-String $item.ImageUrl
    $name = Sql-String $item.Name
    $copyrightType = Sql-String $item.CopyrightType
    $sourceImageId = Sql-String $item.SourceImageId
    $provider = Sql-String $item.Provider
    $sourcePageUrl = Sql-String $item.SourcePageUrl
    $licenseUrl = Sql-String $item.LicenseUrl
    $attribution = Sql-String $item.Attribution
    $verifiedAt = Sql-String $item.VerifiedAt

    $lines.Add("UPDATE tourist_spot SET thumbnail_url = $url, original_image_url = $url WHERE id = $spotId AND active = 1;")
    $lines.Add("INSERT INTO tourist_spot_image (tourist_spot_id, url, alt_text, sort_order, copyright_type, source_image_id, source_provider, source_page_url, license_url, attribution, verified_at) SELECT $spotId, $url, $name, 0, $copyrightType, $sourceImageId, $provider, $sourcePageUrl, $licenseUrl, $attribution, $verifiedAt FROM DUAL WHERE EXISTS (SELECT 1 FROM tourist_spot WHERE id = $spotId AND active = 1) AND NOT EXISTS (SELECT 1 FROM tourist_spot_image WHERE tourist_spot_id = $spotId AND source_image_id = $sourceImageId);")
}

$lines.Add('COMMIT;')
$lines | Set-Content -LiteralPath $outputPath -Encoding utf8NoBOM
Write-Host "Generated $($approved.Count) image assignments at $outputPath"
